### PR TITLE
Call xref-location-marker lazily and do not sort candidates

### PR DESCRIPTION
**Pull request by MaskRay**
xref-location-marker calls `(cl-defmethod xref-location-marker ((l xref-file-location)) ...)`,
which creates buffers for each non-visiting file and may be slow.

Remove :candidate-transformer because this is better done on the xref
source side.

### CODE REVIEW

**Comment by MaskRay** [comment]
This should fix https://github.com/brotzeit/helm-xref/issues/6

**Comment by MaskRay** [comment]
`:candidate-transformer` is annoying because the sorting should be done on the xref backend's side. For example, cquery sorts `workspace/symbol` candidates by their relevance.

**Comment by brotzeit** [comment]
Thanks! Do you think it would also be better to kill buffers that were only displayed by `persistent-action` and not actually visited ?

**Comment by MaskRay** [comment]
I am unclear. If the user hit `TAB` to trigger `:persistent-action`, it manifests the user's intention to visit the file, then it may be fine to leave the visited file opened. 

Now I can get rid of my `xref-find-apropos` hack in favor of helm-xref's.

**Comment by brotzeit** [comment]
I see `persistent-action` more as a preview. If I want to actually visit the file I have to use `action`.

**Pull request merged**
